config/routes.rb
Rails.application.routes.draw do
  namespace :blog do
    resources :posts do
      collection do
        get 'list'
        get 'show_list'
        get 'tags/:tag', to: 'posts#list', as: "tag"
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/blog/post.rb
module Blog
  class Post < ApplicationRecord
    validates_presence_of :title, :user_id, :body
    belongs_to :user
    has_many :taggings
    has_many :tags, through: :taggings
    has_many :comments,class_name: 'Comment::Comment', as: :commentable

    def self.tagged_with(name)
      Tag.find_by_name!(name).posts.where('? >= published_at and draft = ?', DateTime.now, false).includes(:user)
    end

    def text
       return teaser if teaser.present? and !teaser.blank?
       body if body.present? and !body.blank?
    end

    def reading_time
      words_per_minute = 150
      text = Nokogiri::HTML(self.body).at('body').inner_text
      (text.scan(/\w+/).length / words_per_minute).to_i
    end

    def all_tags=(names)
      self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
      end
    end

    def all_tags
      self.tags.map(&:name).join(", ")
    end

  end
end

app/models/blog/tag.rb
class Blog::Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("blog_tags.name, count(blog_taggings.tag_id) as count").joins(:taggings).group("blog_taggings.tag_id,blog_tags.name")
  end
end

app/models/blog/tagging.rb
class Blog::Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < ApplicationController
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy, :show_list]
    before_action :authenticate_user!, except: [:list, :show_list]
    load_and_authorize_resource except: [:list, :show_list, :create]
    # GET /blog/posts
    def index
      if params[:tag]
        @blog_posts = Post.tagged_with(params[:tag]).page params[:page]
      else
        @blog_posts = Post.all.page params[:page]
      end
    end

    def list
      if params[:tag]
        @blog_posts = Post.tagged_with(params[:tag]).page params[:page]
      else
        @blog_posts = Post.where('? >= published_at and draft = ?', DateTime.now, false).includes(:user).page params[:page]
      end
    end

    # GET /blog/posts/1
    def show
    end

    def show_list
      @blog_post.increment!(:access_count)
    end

    # GET /blog/posts/new
    def new
      @blog_post = Post.new
    end

    # GET /blog/posts/1/edit
    def edit
    end

    # POST /blog/posts
    def create
      authorize! :create, @blog_post
      @blog_post = Post.new(blog_post_params)
      @blog_post.user_id = current_user.id

      if @blog_post.save
        redirect_to @blog_post, notice: 'Post was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /blog/posts/1
    def update
      if @blog_post.update(blog_post_params)
        redirect_to @blog_post, notice: 'Post was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /blog/posts/1
    def destroy
      @blog_post.destroy
      redirect_to blog_posts_url, notice: 'Post was successfully destroyed.'
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :teaser, :body, :draft, :published_at, :user_id, :custom_url, :access_count,:all_tags)
    end
  end
end

app/helpers/blog/posts_helper.rb
module Blog::PostsHelper

  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, list_blog_posts_path(tag:tag.strip) }.join(", ")
  end

  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

app/views/blog/posts/_collection.html.erb
<% collection.each do |resource| %>
    <tr id="<%= dom_id(resource) %>">
      <td><%= resource.title %></td>
      <td><%= raw(resource.teaser)  %></td>
      <td><%= resource.draft %></td>
      <td><%= converte_date(resource.published_at) %></td>
      <td><%= resource.user_id %></td>
      <td><%= resource.access_count %></td>
      <td class="text-center">
        <% if current_user and current_user.admin? %>
            <%= resource.decorate.link_to_show %>
            <%= resource.decorate.link_to_edit %>
            <%= resource.decorate.link_to_delete %>
        <% end %>
      </td>
      </td>
    </tr>
<% end %>

app/views/blog/posts/_collection_list.html.erb
<% collection.each do |resource| %>
    <div class="block" id="<%= dom_id(resource) %>">
      <div class="block-content">
        <div class="row items-push">
          <!--<div class="col-md-4">-->
            <!--<a href="frontend_blog_story.php">-->
              <!--<img class="img-responsive" src="https://wallpaperbrowse.com/media/images/html-color-codes-color-tutorials-hero-00e10b1f.jpg" alt="">-->
            <!--</a>-->
          <!--</div>-->
          <div class="col-md-12">
            <div class="font-s12 push-10">
              <em class="pull-right"><%=pluralize(resource.reading_time, 'minuto')%></em>
             <%= resource.decorate.link_to_author %> - publicado em <%= converte_date(resource.published_at) %>
            </div>
            <h4 class="text-uppercase push-10">
              <%= resource.decorate.link_to_title %></h4>
            <p>
              <% if resource.teaser.present? %>
                  <%= raw resource.text %>
              <% else %>
                  <%= raw Truncato.truncate resource.text, max_length: 150, count_tags: false%>
              <% end %>
            </p>
            <div class="btn-group btn-group-sm">
              <!--<a class="btn btn-default" href="javascript:void(0)"><i class="fa fa-share-alt push-5-r"></i> Compartilhar</a>-->
              <%= resource.decorate.link_to_read_more %>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/blog/posts/_form.html.erb
<%= simple_form_for @blog_post, class: "form-horizontal" do |f| %>
    <%= f.error_notification %>


    <%= f.input :title, id: :blog_post_title %>

    <%= f.input :teaser, as: :summernote %>
    <%= f.input :body, as: :summernote %>
    <%#= f.input :teaser, class: 'summernote', :id => 'blog_post_teaser' , label: false%>
    <%#= f.input :body, class: 'summernote', :id => 'blog_post_body', label: false %>
    <%= f.input :draft, id: :blog_post_draft %>

    <%= f.input :published_at, id: :blog_post_published_at %>

    <%= f.input :custom_url, id: :blog_post_custom_url %>

    <%= f.input :all_tags, placeholder: "Tags separated with comma" %>

    <div class="form-group form-actions">
      <%= link_to I18n.t('misc.action.back'), blog_posts_path, class: 'btn btn-sm btn-square btn-default' %>
      <%= f.button :submit, class: 'btn btn-sm btn-square btn-primary' %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function () {
        $('#blog_post_teaser').summernote({
            lang: 'pt-BR',
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });
        $('#blog_post_body').summernote({
            lang: 'pt-BR',
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });
    });
</script>

app/views/blog/posts/_pagination.html.erb
<div class="paging_simple_numbers">
  <%= paginate collection %>
</div>

app/views/blog/posts/edit.html.erb
<%= provide :page_title, I18n.t('blog_posts.new.header') %>
<%= provide :breadcrumb do %>
    <li><%= link_to  t('activerecord.models.blog_post.other'), links_path %></li>
    <li><%=t 'blog_posts.new.header' %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= I18n.t('blog_posts.new.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</main>

app/views/blog/posts/index.html.erb
<%= provide :page_title, I18n.t('blog_post.index.header') %>
<%= provide :breadcrumb do %>
    <li><%= I18n.t('activerecord.models.blog_post.other') %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= t('blog_posts.index.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-header text-right">
        <h3 class="block-title">
        </h3>
        <span >
          <%= link_to I18n.t('blog_post.new.header'), new_blog_post_path, class: 'btn btn-sm btn-square btn-success' %>
        </span>
      </div>
      <div class="block-content">
        <table class="table table-striped">
          <thead>
          <tr>
            <th><%=t 'activerecord.attributes.blog_post.title' %></th>
            <th><%=t 'activerecord.attributes.blog_post.teaser' %></th>
            <th><%=t 'activerecord.attributes.blog_post.draft' %></th>
            <th><%=t 'activerecord.attributes.blog_post.published_at' %></th>
            <th><%=t 'activerecord.attributes.blog_post.access_count' %></th>
            <th class="text-center" style="width: 150px;"><%=t 'misc.actions' %></th>
          </tr>
          </thead>
          <tbody id='blog_posts'>
          <%= render 'collection', collection: @blog_posts %>
          </tbody>
        </table>
        <%=render 'pagination',collection: @blog_posts%>

      </div>
    </div>
  </div>
</main>

app/views/blog/posts/list.html.erb
<main id="main-container" style="min-height: 190px;"><div class="bg-primary-dark">
  <section class="content content-full content-boxed overflow-hidden">
    <div class="push-100-t push-50 text-center">
      <h1 class="h2 text-white push-10 animated fadeInDown" data-toggle="appear" data-class="animated fadeInDown">As Últimas Notícias Para você .</h1>
      <h2 class="h5 text-white-op animated fadeInDown" data-toggle="appear" data-class="animated fadeInDown">Explore.</h2>
    </div>
  </section>
</div>
  <section class="content content-boxed">
    <div class="push-50-t push-50">
      <div class="row">
        <div class="col-md-12">




          <%= render 'collection_list', collection: @blog_posts %>




          <!--<nav>-->
            <!--<ul class="pagination">-->
              <!--<li class="active">-->
                <!--<a href="javascript:void(0)">1</a>-->
              <!--</li>-->
              <!--<li>-->
                <!--<a href="javascript:void(0)">2</a>-->
              <!--</li>-->
              <!--<li>-->
                <!--<a href="javascript:void(0)">3</a>-->
              <!--</li>-->
              <!--<li>-->
                <!--<a href="javascript:void(0)">4</a>-->
              <!--</li>-->
              <!--<li>-->
                <!--<a href="javascript:void(0)">5</a>-->
              <!--</li>-->
              <!--<li>-->
                <!--<a href="javascript:void(0)"><i class="fa fa-angle-right"></i></a>-->
              <!--</li>-->
            <!--</ul>-->
          <!--</nav>-->
          <%=render 'pagination',collection: @blog_posts%>

        </div>
        <!--<div class="col-md-4">-->
          <!--<div class="block">-->
            <!--<div class="block-header bg-gray-lighter">-->
              <!--<h3 class="block-title">Search</h3>-->
            <!--</div>-->
            <!--<div class="block-content block-content-full">-->
              <!--<form action="frontend_search.php" method="post">-->
                <!--<div class="input-group input-group-lg">-->
                  <!--<input class="form-control" type="text" placeholder="Type and hit enter..">-->
                  <!--<div class="input-group-btn">-->
                    <!--<button class="btn btn-default"><i class="fa fa-search"></i></button>-->
                  <!--</div>-->
                <!--</div>-->
              <!--</form>-->
            <!--</div>-->
          <!--</div>-->
          <!--<a class="block block-link-hover3" href="base_pages_profile.php">-->
            <!--<div class="block-header bg-gray-lighter">-->
              <!--<h3 class="block-title">About</h3>-->
            <!--</div>-->
            <!--<div class="block-content block-content-full text-center">-->
              <!--<div>-->
                <!--<img class="img-avatar img-avatar96" src="assets/img/avatars/avatar1.jpg" alt="">-->
              <!--</div>-->
              <!--<div class="h5 push-15-t push-5">Ann Parker</div>-->
              <!--<div class="font-s13 text-muted">Publisher</div>-->
            <!--</div>-->
            <!--<div class="block-content border-t">-->
              <!--<div class="row items-push text-center">-->
                <!--<div class="col-xs-6">-->
                  <!--<div class="push-5"><i class="si si-pencil fa-2x"></i></div>-->
                  <!--<div class="h5 font-w300 text-muted">350 Stories</div>-->
                <!--</div>-->
                <!--<div class="col-xs-6">-->
                  <!--<div class="push-5"><i class="si si-users fa-2x"></i></div>-->
                  <!--<div class="h5 font-w300 text-muted">1.5k Followers</div>-->
                <!--</div>-->
              <!--</div>-->
            <!--</div>-->
          <!--</a>-->
          <!--<div class="block">-->
            <!--<div class="block-header bg-gray-lighter">-->
              <!--<ul class="block-options">-->
                <!--<li>-->
                  <!--<button type="button" data-toggle="block-option" data-action="refresh_toggle" data-action-mode="demo"><i class="si si-refresh"></i></button>-->
                <!--</li>-->
              <!--</ul>-->
              <!--<h3 class="block-title">Recent Comments</h3>-->
            <!--</div>-->
            <!--<div class="block-content">-->
              <!--<ul class="list list-simple">-->
                <!--<li>-->
                  <!--<div class="push-5 clearfix">-->
                    <!--<span class="font-s13 text-muted push-10-l pull-right">25 min ago</span>-->
                    <!--<a class="font-w600" href="base_pages_profile.php">Sara Holland</a> on <a href="frontend_blog_story.php">Exploring the Alps</a>-->
                  <!--</div>-->
                  <!--<div class="font-s13">Awesome trip! Looking forward going there, I'm sure it will be a great experience!</div>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<div class="push-5 clearfix">-->
                    <!--<span class="font-s13 text-muted push-10-l pull-right">42 min ago</span>-->
                    <!--<a class="font-w600" href="base_pages_profile.php">Joshua Munoz</a> on <a href="frontend_blog_story.php">Travel &amp; Work</a>-->
                  <!--</div>-->
                  <!--<div class="font-s13">Thank you for sharing your story with us! I really appreciate the info, it will come in handy for sure!</div>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<div class="push-5 clearfix">-->
                    <!--<span class="font-s13 text-muted push-10-l pull-right">53 min ago</span>-->
                    <!--<a class="font-w600" href="base_pages_profile.php">Lisa Gordon</a> on <a href="frontend_blog_story.php">Black &amp; White</a>-->
                  <!--</div>-->
                  <!--<div class="font-s13">Really touching story.. I'm so happy everything went well at the end!</div>-->
                <!--</li>-->
                <!--<li>-->
                  <!--<div class="push-5 clearfix">-->
                    <!--<span class="font-s13 text-muted push-10-l pull-right">2 days ago</span>-->
                    <!--<a class="font-w600" href="base_pages_profile.php">George Stone</a> on <a href="frontend_blog_story.php">Sleep Better</a>-->
                  <!--</div>-->
                  <!--<div class="font-s13">Great advice! Thanks for sharing, I'm sure it will help many people sleep better and improve their lifes.</div>-->
                <!--</li>-->
              <!--</ul>-->
              <!--<div class="text-center push">-->
                <!--<small><a href="javascript:void(0)">Read More..</a></small>-->
              <!--</div>-->
            <!--</div>-->
          <!--</div>-->
          <!--<div class="block">-->
            <!--<div class="block-header bg-gray-lighter">-->
              <!--<h3 class="block-title">Social</h3>-->
            <!--</div>-->
            <!--<div class="block-content block-content-full">-->
              <!--<div class="btn-group">-->
                <!--<a class="btn btn-default" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Follow us on Twitter"><i class="fa fa-fw fa-twitter"></i></a>-->
                <!--<a class="btn btn-default" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Like our Facebook page"><i class="fa fa-fw fa-facebook"></i></a>-->
                <!--<a class="btn btn-default" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Follow us on Google Plus"><i class="fa fa-fw fa-google-plus"></i></a>-->
                <!--<a class="btn btn-default" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Follow us on Dribbble"><i class="fa fa-fw fa-dribbble"></i></a>-->
                <!--<a class="btn btn-default" href="javascript:void(0)" data-toggle="tooltip" title="" data-original-title="Subscribe on Youtube"><i class="fa fa-fw fa-youtube"></i></a>-->
              <!--</div>-->
            <!--</div>-->
          <!--</div>-->
        <!--</div>-->

      </div>
    </div>
  </section>
  <div class="bg-primary-dark">
    <section class="content content-full content-boxed">
      <div class="push-20-t push-20 text-center">
        <div class="tags-cloud glassy-bg">
          <h4>Nuvem de Tags</h4>
          <% tag_cloud Blog::Tag.counts, %w{css1 css2 css3 css4} do |tag, css_class| %>
              <%= link_to tag.name, list_blog_posts_path(tag:tag.name), class: css_class %>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</main>

app/views/blog/posts/new.html.erb
<%= provide :page_title, I18n.t('blog_posts.new.header') %>
<%= provide :breadcrumb do %>
    <li><%= link_to  t('activerecord.models.blog_post.other'), links_path %></li>
    <li><%=t 'blog_posts.new.header' %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= I18n.t('blog_posts.new.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-content">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</main>

app/views/blog/posts/show.html.erb
<%= provide :page_title, I18n.t('blog_posts.show.header', resource: @blog_post.try(:id)) %>
<%= provide :breadcrumb do %>
    <li><%= link_to I18n.t('activerecord.models.blog_posts.other'), links_path %></li>
    <li><%= link_to @blog_post.try(:id), @blog_post %></li>
    <li><%= I18n.t('blog_posts.show.header', resource: @blog_post.try(:id)) %></li>
<% end %>

<main id="main-container" style="min-height: 530px;">
  <div class="content bg-gray-lighter">
    <div class="row items-push">
      <div class="col-sm-7">
        <h1 class="page-heading">
          <%= t('blog_posts.show.title') %>
        </h1>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="block">
      <div class="block-header text-right">
        <h3 class="block-title">
        </h3>
        <span>
          <%= link_to I18n.t('blog_posts.new.new'), new_blog_post_path, class: 'btn btn-sm btn-square btn-success' %>
        </span>
      </div>
      <div class="block-content">
        <div class="row">

          <div class="col-sm-12">
            <table class="table table-striped">
              <thead>
              </thead>
              <tbody>
              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.title' %>:</strong></td>
                <td><%= @blog_post.title %></td>
              </tr>

              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.teaser' %>:</strong></td>
                <td><%= @blog_post.teaser.html_safe %></td>
              </tr>

              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.body' %>:</strong></td>
                <td><%= @blog_post.body.html_safe %></td>
              </tr>

              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.draft' %>:</strong></td>
                <td><%= @blog_post.draft %></td>
              </tr>

              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.published_at' %>:</strong></td>
                <td><%= @blog_post.published_at %></td>
              </tr>

              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.custom_url' %>:</strong></td>
                <td><%= @blog_post.custom_url %></td>
              </tr>

              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.access_count' %>:</strong></td>
                <td><%= @blog_post.access_count %></td>
              </tr>
              <tr>
                <td><strong><%= t 'activerecord.attributes.blog_post.tags' %>:</strong></td>
                <td><%=raw tag_links(@blog_post.all_tags)%></td>
              </tr>


              </tbody>
            </table>
          </div>
        </div>
        <div class="row">

          <div class="col-sm-4 ">
            <%= link_to I18n.t('misc.action.back'), blog_posts_path, class: 'btn btn-default' %>
            <%= link_to I18n.t('misc.action.edit'), edit_blog_post_path(@blog_post), class: 'btn btn-warning' %>
            <%= link_to I18n.t('misc.action.destroy'), blog_post_path(@blog_post), method: :destroy, data: {confirm: I18n.t('blog_post.show.remover')}, class: 'btn btn-danger' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/blog/posts/show_list.html.erb
<main id="main-container" style="min-height: 190px;"><div class="bg-image" style="background-image: url('<%=asset_path "railswall.jpg"%>');">
  <div class="bg-primary-op">
    <section class="content content-full content-boxed overflow-hidden">
      <div class="push-150-t push-150 text-center">
        <h1 class="text-white push-10 animated fadeInDown" data-toggle="appear" data-class="animated fadeInDown"><%= @blog_post.title %></h1>
      </div>
    </section>
  </div>
</div>
  <div class="bg-white">
    <section class="content content-boxed">
      <div class="text-center">
        <%= @blog_post.decorate.link_to_author %> <% if @blog_post.published_at or (current_user and current_user.admin?) %> - <% end %> <%= converte_timestamp(@blog_post.published_at) %> <% if current_user and current_user.admin? %><em>visualizado <%=@blog_post.access_count%> <% end %></em>
      </div>
      <div class="row push-50-t push-50 nice-copy-story">
        <div class="col-sm-8 col-sm-offset-2">
          <p><%= @blog_post.body.html_safe %></p>


        </div>
      </div>

    </section>

    <section class="content content-boxed">

      <div class="row push-50-t push-50 nice-copy-story">
        <div class="col-sm-8 col-sm-offset-2">


          <%=render 'comment/comments/comments',comments:@blog_post.comments%>

        </div>
      </div>

    </section>
  </div>

  <section class="content content-full content-boxed">
    <div class="push-20-t push-20 text-center">
      <h3 class="h4 text-white-op push-20 animated fadeIn" data-toggle="appear"> <%=raw tag_links(@blog_post.all_tags)%></h3>
    </div>
  </section>

</main>